unicode-org/conformance

executors/README.md

This is a start on documentation of executors function, inputs, and outputs.

Executor: Add readme.md describing executors

---

executors/rust/Cargo.toml
generateDataAndRun.sh

There seems to be a version ambiguity that is affecting the Rust compilation on CI.
PR #59 is [failing CI](https://github.com/unicode-org/conformance/actions/runs/4942064491/jobs/8835849491) in the Rust build even though it has not updated Rust code.

Fix Rust build errors

---

executors/node/executor.js
executors/node/langnames.js
testdriver/datasets.py
testdriver/ddtargs.py
testdriver/testplan.py
testgen/numberpermutationtest.txt
testgen/testdata_gen.py
verifier/report_template.py
verifier/testreport.py
verifier/verifier.py

This updates lots of things, including a start on loading data via JSON fetch. It also restructures the directory structure, creating subdirectories with versions under testResults/node and testResults/rust.
├── node
│   ├── v16.19.1
│   │   ├── coll_shift_short
│   │   │   ├── coll_test_shift.html
│   │   │   ├── coll_test_shift.json
│   │   │   ├── failing_tests
│   │   │   │   └── failing_tests.json
│   │   │   ├── pass
│   │   │   │   └── pass.json
│   │   │   ├── test_errors
│   │   │   │   └── test_errors.json
│   │   │   └── unsupported
│   │   │       └── unsupported.json
│   │   ├── lang_names
│   │   │   ├── failing_tests
│   │   │   │   └── failing_tests.json
│   │   │   ├── lang_name_test_file.html
│   │   │   ├── lang_name_test_file.json
│   │   │   ├── pass
│   │   │   │   …

Fix num options

---

verifier/detail_template.html

This updates the detail HTML page with filtering failed tests by a combination of characterizations, e.g., "locale" or "scientific notation" or "Insert digit". These are shown in a sub-table of Failing Tests as "Failures Categorized". The subset of failures show is the intersection of the sets of individual characterizations.

Fix selection of failing characteristics

---

.github/workflows/gcs-upload.yml

I think GitHub is blocking access to the GCP secret from PRs.

Don't run artifacts build on PRs

---

genData100.sh
generateDataAndRun.sh
testdriver/ddtargs.py
testdriver/runCollNum_ALL.sh
testdriver/runColl_ALL.sh
testdriver/runColl_python.sh
testdriver/runNum_python.sh

...according to the common wisdom that it is preferable to explicitly use `python3` when invoking Python 3, rather than just `python`.

Replace `python` with `python3`

---

.gitignore
logging.conf
schema/check_generated_data.py
schema/check_schemas.py
schema/check_test_output.py
schema/schema_validator.py
testdriver/testdriver.py
testdriver/testplan.py
testgen/testdata_gen.py
verifier/report_template.py
verifier/testreport.py
verifier/verifier.py

Formats logging output so that it simultaneously saves to a file and prints to the console.  The console looks like:
```
...
[2023-11-17 16:04:59,343] [WARNING]  VALIDATION WORKS: collation_short icu69
[2023-11-17 16:04:59,343] [INFO]  Checking collation_short, icu70
[2023-11-17 16:04:59,343] [INFO]  Validating collation_short with icu version icu70
[2023-11-17 16:05:12,297] [INFO]  This test output file validates: ../TEMP_DATA/testData/icu70/collation_test.json, ./collation_short/test_schema.json:
[2023-11-17 16:05:12,371] [INFO]  Test data collation_short validated successfully, with ICU icu70
{'test_type': 'collation_short', 'icu_version': 'icu70', 'result': True, 'err_info': None, 'test_schema': './collation_short/test_schema.json', 'data_file_name': …
```

Add logging configuration

---

executors/icu4j/73/executor-icu4j/pom.xml
executors/icu4j/73/executor-icu4j/src/main/java/org/unicode/conformance/Icu4jExecutor.java
executors/icu4j/73/executor-icu4j/src/test/java/org/unicode/conformance/Icu4jExecutorTest.java
generateDataAndRun.sh
run_config.json
testdriver/datasets.py
testdriver/ddtargs.py
testdriver/testdriver.py
testdriver/testplan.py

Add an empty implementation for an ICU4J executor.  Also, add an option to running an executor (called `--ignore`) that allows a new executor instance to be skipped.

Add ICU4J executor skeleton implementation

---

executors/dart_web/bin/likely_subtags.dart
executors/dart_web/bin/numberformat.dart

This adds information to test results that identify them as unsupported rather than errors. The results should be very similar to those of the NodeJS version.
Please review these proposed changes.

Reclassify Dart results - many to unsupported

---

testgen/testdata_gen.py

This updates some of the tests to reset the base string to empty when a new comparison set is started.
This improves passing tests in
Node icu74: from 372,031 --> 372,129
Dart icu73:  from 371,961 --> 372,062
No change in ICU4X, however.
A small improvement, removing about 5% of the failing tests.

Updating collation generation and execution

---

executors/rust/1.3/Cargo.lock
executors/rust/1.3/Cargo.toml
executors/rust/1.3/build.rs
executors/rust/1.3/src/decimalfmt.rs
executors/rust/1.3/src/displaynames.rs
executors/rust/1.3/src/main.rs
executors/rust/1.3/src/numberfmt.rs
executors/rust/1.4/Cargo.lock
executors/rust/1.4/Cargo.toml

Removed unnecessary deps, included dead modules, moved version detection into build.rs

Cleaning up Rust executor

---

executors/rust/1.3/src/collator.rs

See #129
I made this change directly in the GitHub UI so I haven't tested it yet. Hopefully CI is helpful :)

Rust executor: check is_le instead of is_lt

---

executors/dart_native/bin/executor.dart
executors/dart_web/bin/lang_names.dart
executors/dart_web/bin/lang_namesExecutor.dart
executors/dart_web/out/executor.js
executors/dart_web/out/lang_names.js
executors/dart_web/pubspec.yaml
run_config.json

Add testing for `lang_names` for Dart Web using `package:intl4x`.

Dart add `lang_names` testing

---

setup.sh
testgen/testdata_gen.py

For certain use-cases, it is convenient to generate the JSONs for one test type rather than generating all tests each time (for example, when adding a new test type with a different schema). Passing a flag to the script is cleaner than making temporary code changes during development.
This PR adds that flag, which can be used as follows:
Run all tests (pre-existing behavior):
```
python testdata_gen.py --icu_versions icu74
```
Run a subset:
```
python testdata_gen.py --icu_versions icu74 --test_types number_fmt lang_names
```

Add optional test_types flag to testdata_gen script

---

run_config.json

An error in Dart Native is blocking continuous integration of updates. This PR removes dart_native so the CI can work again.
"The problem is the use of the @ResourceIdentifier annotation in package:intl4x, introduced by https://github.com/dart-lang/i18n/pull/795. The implementation was faulty, which is now fixed in the Dart SDK. To not get an error, pin the version of intl4x to an earlier one (but that will probably also mean losing all new features introduced since), or wait for the implementation in the Dart SDK to propagate into the newest version, which should be quite soon."

Temporarily remove dart_native from platforms

---

executors/rust/1.3/src/listfmt.rs
executors/rust/1.3/src/main.rs
executors/test_strings.txt
run_config.json
schema/list_fmt/test_schema.json
testgen/generators/list_fmt_gen.js

Add another field list_type. The field "type" in list_fmt data is now deprecated.

ICU4X: Adding list format testing

---

schema/message_fmt2/testgen_schema.json
testgen/icu75/message_fmt2/message-format-wg-tests/functions/date.json
testgen/icu75/message_fmt2/message-format-wg-tests/functions/datetime.json
testgen/icu75/message_fmt2/message-format-wg-tests/functions/number.json
testgen/icu75/message_fmt2/message-format-wg-tests/functions/time.json

Update the error list in testgen_schema.json to match the schema in the MFWG spec repo,
https://github.com/unicode-org/message-format-wg/blob/main/test/schemas/v0/tests.schema.json
Also update function tests to match the schema (just copied the tests from the current MFWG spec repo).

message_fmt2: Update error types in schema

---

schema/message_fmt2/testgen_schema.json

Add properties to schema that are used in ICU tests: 'char', 'line', 'comment', 'srcs', 'ignoreJava', and 'ignoreCpp'

message_fmt2: Add more properties to schema

---

schema/message_fmt2/testgen_schema.json

This error was recently added to the spec
(see https://github.com/unicode-org/message-format-wg/commit/5612f3b0508d63770b218d581c465aae878f5573 )

message_fmt2: Add duplicate-variant error

---

executors/cpp/relativedatetime_fmt.cpp
executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/relativedatetimeformat/RelativeDateFormatNumeric.java
executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/relativedatetimeformat/RelativeDateTimeFormatInputJson.java
executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/relativedatetimeformat/RelativeDateTimeFormatTester.java
executors/icu4j/74/executor-icu4j/src/test/java/org/unicode/conformance/relativedatetimeformat/icu74/RelativeDateTimeFormatTest.java
testgen/generators/rdt_fmt_gen.js

This fixes lots of the test failures with RDTF. It adds tests for numeric with "auto" and "always" options.

relative date time format: add numeric options and use in format testing

---

testgen/README.md
testgen/icu73/localeDisplayName.txt
testgen/icu74/localeDisplayName.txt
testgen/icu75/localeDisplayName.txt

Manually repeated commands to checkout CLDR, checkout the updated test data generator (added in CLDR post-v45), run the new test data generator on the old repo & its data snapshot, to produce the retroactive generated test files.
Ex for CLDR 43/ICU 73:
```
git co release-43 -b release-43-ddt-datagen
git checkout main -- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLocaleIDTestData.java
pushd tools/cldr-code
mvn compile exec:java -DCLDR_DIR=/usr/local/google/home/elango/oss/cldr/mine/src -Dexec.mainClass=org.unicode.cldr.tool.GenerateLocaleIDTestData
popd
cp ./common/testData/localeIdentifiers/localeDisplayName.txt ~/oss/conformance/testgen/icu73
```

Add generated CLDR test data for locale display names for ICU v73-75

---

executors/rust/1.3/src/relativedatetime_fmt.rs

This should be removed when numbering systems are better supported.
close #287

ICU4X rel date time -  non-Latn number system --> unsupported

---

testgen/icu75/ordinals.xml

This data was missing and simply needs to be added to the input for generating test cases.

Add missing plural rules ordinals test data for ICU75

---

testgen/generators/datetime_gen.js
testgen/generators/list_fmt_gen.js
testgen/generators/rdt_fmt_gen.js
verifier/testreport.py

This reduces test failures because the "und" locale can produce platoform-specific results.

Remove 'und' as a locale in testing

---

schema/message_fmt2/testgen_schema.json

* Add `bidiIsolation` property that was recently added
* Remove `expCleanSrc` property that is no longer used
* Add "Bidi isolation part" variant to `expParts`
* Remove `unsupported-statement` and `unsupported-expression` from enum in `expErrors`

message_fmt2: Make schema more consistent with schema in WG repo

---

verifier/testreport.py

For plural_rules, now check for sample type including integer, float, exponential, and compact.
For datetime_fmt, collect skeleton info.
For locale_display_names, characterize () --> [] and the reverse.

Update characterization for plural_rules, datetime skeletons, and other small changes

---

run_config.json
testdriver/datasets.py
testgen/generators/datetime_fmt.py
testgen/generators/list_fmt.py
testgen/generators/relativedatetime_fmt.py

This also adds ICU76 testing for list format and relative date time because those generators use NodeJS data.

Add NodeJS 23.3.0 supporting ICU76

---

schema/collation_short/test_schema.json
testgen/generators/base.py
testgen/generators/collation_short.py
verifier/testreport.py

This fixes a lot of problems with parsing the Unicode test file collationtest.txt, handling the begin/end of regions of the data more carefully. This results in adding a few more tests (150 added in ICU75) as well as adding some attributes.
A new step is to use these attributes correctly in executors to compute the differences correctly.

Better parsing of collationtest.txt data

---

verifier/summary_template.html

#350 
This PR affects the links to detail pages, e.g., ICU4C testing of list_format in ICU76.
If there are no fail tests or error results, then the link may be of different colors:
* All pass --> green background
* All either pass or are unsupported --> gray background
* All either pass or are known issues --> light orange background.

Change link color depending on passing status

---

executors/node/collator.js
schema/collation_short/result_schema.json
testgen/generators/base.py
testgen/generators/collation_short.py

This moves all Node errors to "unsupported" or "fail". It also outputs the actual options that NodeJS used in a failing tests.

Node and collation: fix errors, add 'actual_options'

---

testgen/generators/relativedatetime_fmt.py

This now solves RDT formatting in NodeJS, ICU4C, and ICU4J with version 76!

Update RDTF code generation to use latest nodejs data

---

executors/dart_native/bin/executor.dart
run_config.json

Reverts unicode-org/conformance#385
We've encountered issues when running the pipeline from end to end, both locally and in CI. The current hypothesis is documented in #388.

Revert "Add more dart versions: 74, 75, and 76"

---

executors/dart_web/out/executor.js

Printing out every case where "error" is in the output is unnecessary and produces huge numbers of log lines.

Dart web: remove extraneous debug output

---

.github/workflows/e2e.yml

We need to fix the upload action. Here's the notice that is causing PR #393 to fail: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update upload-artifact version

---

executors/dart_web/bin/make_runnable_by_node.dart
executors/dart_web/out/executor.js
executors/dart_web/pubspec.yaml

Make it a bit less fragile by using `package:node_preamble`.

Make Dart to Node executable more robust

---

executors/node/plural_rules.js

Based on this issue https://github.com/tc39/ecma402/issues/397, this fixes plural rules with floating point numbers:

NodeJS plural rules: fix floating point tests

---

executors/rust/2.0-beta1/Cargo.toml
executors/rust/2.0-beta1/build.rs
executors/rust/2.0-beta2/Cargo.toml
executors/rust/2.0-beta2/build.rs
executors/rust/common/print_modern_locales.rs
executors/rust/src/compat.rs
executors/rust/src/pluralrules.rs

Improves ICU4X plurals conformance.
However, I think we should just not emit the non-modern locales in test data gen.

Skip unsupported locales in plural rules test in ICU4X

---

executors/icu4j/74/executor-icu4j/src/test/java/org/unicode/conformance/pluralrules/icu74/PluralRulesTest.java
verifier/check_known_issues.py

This should be solved with better handling of precision, but there's no public API.

Plural rules ICU4J handle known issue with '4.1'

---

executors/rust/src/datetime_2_beta2.rs

Not yet completely done, but it brings the number of errors from ~90 down to 12 and successes from 0 to 25.

Improve ICU4X beta2 datetime executor

---

executors/cpp/datetime_fmt.cpp
executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/datetimeformatter/DateTimeFormatterTester.java
executors/icu4j/74/executor-icu4j/src/test/java/org/unicode/conformance/datetimeformatter/DateTimeFormatterTest.java
schema/datetime_fmt/test_schema.json
testgen/generators/datetime_fmt.py

This updates the date time test generator to put skeleton data into options.
Also, it adds two new options yearStyle and zoneStyle from CLDR as needed by ICU4X.

DateTime: Move skeleton data to options, add new CLDR data options

---

.github/workflows/e2e.yml

Lots of CI end-to-end workflow instances are failing in PRs and on `main`. The errors in the workflow logs only pertain to Dart, and they indicate a version that is newer. A local run of the end-to-end script succeeds successfully, and a stable version of Dart is being used.
This will turn off using unstable versions of Dart so that we still to stable ones. 
Hopefully, this will fix the noisy CI errors that are getting in the way of unrelated PRs.

Use stable version of Dart in CI

---

executors/cpp/number_fmt.cpp
executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/numberformatter/NumberFormatterOutputJson.java
executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/numberformatter/NumberFormatterTester.java
executors/icu4j/74/executor-icu4j/src/test/java/org/unicode/conformance/numberformatter/icu74/NumberFormatterTest.java
executors/node/numberformat.js
schema/number_format/result_schema.json
schema/number_format/test_schema.json
testgen/generators/collation.py
testgen/generators/number_fmt.py
verifier/check_known_issues.py
verifier/testreport.py
verifier/verify_plan.py

Fixing problems with number format data generation and executors.
Starting with NodeJS.

Updating number format data generation and NodeJS number_fmt

---

executors/node/collator.js

This acknowledges that -kr- is not supported as a locale extension,
And -co-search is supported as a setting for the "usage" option.

Fix almost all NodeJS collation issues.

---

executors/rust/src/collator.rs

This changes results:
Fail:  317 --> 133
Unsupported: 0 -> 927  (these are the tests with rules that are not yet supported)

ICU4X collation - mark rules as unsupported. Apply strength option.

---

executors/cpp/coll.cpp
executors/cpp/main.cpp
schema/collation/test_schema.json
testgen/generators/base.py
testgen/generators/collation.py

Test generation in Python puts SMP characters (> 0xffff) as \ud8** surrogate pairs. This works OK for ICU4J, ICU4X, and NodeJS, but fails with the current CPP JSON.
This workaround adds two new items that contain the hex codes for the characters to be compared in s1 and s2. These are set for the NON_IGNORABLE and SHIFTED data files.
This is admittedly a hack, but it points out that the tests with SMP characters were not working. With this hack, over 1200 tests now pass that were previously failing.

Use workaround to fix many collation failures in ICU4C.

---

executors/cpp/coll.cpp
executors/cpp/main.cpp
schema/collation/test_schema.json
testgen/generators/base.py
testgen/generators/collation.py

Reverts unicode-org/conformance#475
The CI situation to debug is that that we consistently get "Error: The operation was canceled." on runs of the CI on the latest commit on `main`, as well as at least one currently open PR.

Revert "Use workaround to fix many collation failures in ICU4C."
