unicode-org/conformance

executors/executors.md
This file is not needed, eplaced by the README.md in this directory.
=> Remove duplicate file

DDT_DATA/Small tests.txt, DDT_DATA/coll_test_shift.json, DDT_DATA/lang_name_test_file.json, DDT_DATA/lang_name_verify_file.json, DDT_DATA/num_fmt_test_file.json, DDT_DATA/num_fmt_verify_file.json
These data files are short versions of full test and verify JSON files that can be used to run tests and verify the DDT system.
=> Add short tests and verify info

testdriver/datasets.py
This will allow github actions to run tests in this platform.
=> Change to run 'node' instead of 'nodejs'

executors/rust/src/collator.rs, executors/rust/src/main.rs, executors/rust/src/numberfmt.rs, generateDataAndRun.sh, testdriver/ddtargs.py, testdriver/testdriver.py, testdriver/testplan.py, verifier/testreport.py, verifier/verifier.py, verifier/verifyAll.sh, verifier/verifyNodeJS.sh, verifier/verifyNode_local.sh, verifier/verifyRust.sh, verifier/verifyRust_local.sh
This script runs the test generator, storing testData in a temporary directory. Then it runs testdriver on known tests, creating testResults. These are then verified, producing testReports.
When ready, the test results and test reports will be uploaded to Cloud Storage.
Finally, the temporary directory is removed.
=> Script to get testdata and run tests. Fix testdriver and verifier files.

executors/node/executor.js, executors/node/numberformat.js
Removing console.log statements from node executor
=> Update node noise

generateDataAndRun.sh
Fixes problem with building Rust executor, related #52.
=> Fix generate end-to-end script for pushd

.github/workflows/e2e.yml, generateDataAndRun.sh
=> Add CI job to copy HTML files to Github Pages

testgen/numberpermutationtest.txt, testgen/testdata_gen.py
Updates test generation to fix test errors.
=> Fix bad option in number format for issue #58

testdriver/datasets.py, testdriver/testdriver.py, testdriver/testplan.py, verifier/detail_template.html, verifier/testreport.py, verifier/verifier.py
Resolved most of the coding style issues reported by PyCharm on the Python files.
Small update to detailed report HTML.
=> Removed many Python code warnings

verifier/detail_template.html, verifier/summary_template.html
Updates summary and detail templates with Promises coordinated for data loading, graph drawing, and initializing paginated test results.
=> Use Promise.all to coordinate data loading

.github/workflows/run-nodejs.yml, .gitignore, DDT_DATA/testData/icu71/coll_verify_shift.json, DDT_DATA/testData/icu71/num_fmt_test_file.json, generateDataAndRun.sh, runDDT.sh, testdriver/runAll_node_local.sh, verifier/testreport.py, verifier/verifyNode_local.sh
=> Check that actual and expected result fields exist before comparing

testdriver/datasets.py, testdriver/testplan.py, verifier/detail_template.html, verifier/summary_template.html
Update configuration to correctly handle execution with dart_web.
=> Fixing dart tests

generateDataAndRun.sh, verifier/summary_template.html, verifier/testreport.py, verifier/verifier.py
Updates summary report to correctly show results from dart_web. This now shows graphs and results for all three platforms!
=> Fix verifier to show dart_web output

executors/dart_web/bin/likely_subtags.dart, executors/dart_web/bin/likely_subtagsExecutor.dart, executors/dart_web/bin/make_runnable_by_node.dart, executors/dart_web/out/executor.js, executors/dart_web/out/likely_subtags.js, executors/dart_web/out/version.js, executors/dart_web/pubspec.yaml, generateDataAndRun.sh
Seems to work fine, except for the `minimizeFavorRegion` option where I am unsure what it should map to, as it also does not exist in NodeJs.
=> Add `likely_subtags` to Dart Web

testgen/testdata_gen.py
This resolves hundreds of collation errors due to mismatches in labels between test and verify data files.
=> Fix numbering of collation tests

verifier/summary_template.html, verifier/testreport.py
This adds more information in characterizing test failures. It also changes "rust" to "ICU4X" in the summary page.
=> Change from rust to ICU4X in Summary

executors/dart_web/bin/lang_names.dart, executors/dart_web/bin/make_runnable_by_node.dart, executors/dart_web/out/version.js, executors/dart_web/pubspec.yaml, schema/language_names/result_schema.json, testgen/testdata_gen.py
This allows dart_web for lang_names to start working.
=> Fix some problems with dart_web lang_names

executors/cpp/coll.cpp
This reduces test failures by about 2/3 in collation for ICU4C
=> Set normalization in CPP Collation

testgen/generators/collation_short.py, testgen/testdata_gen.py
Updates to test generation, moving some things to debug.
=> Simplify some test generation output

executors/cpp/main.cpp
This updates the main.cpp to recognize the plural_rules test type.
=> Add plural rules to CPP executor

executors/cpp/Makefile, executors/cpp/main.cpp, executors/cpp/message_fmt2.cpp, executors/cpp/util.cpp, run_config.json
This executes MF2 tests in ICU75.1 and later.
There are some problems with the tests, but this is a start.
=> Adding ICU4C message format2 testing

testgen/generators/base.py, testgen/generators/datetime_fmt.py, testgen/generators/list_fmt.py, testgen/generators/relativedatetime_fmt.py
=> Reclassifying ERRORS in data generation - see issue #238

executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/Icu4jExecutor.java, run_config.json
=> Set ICU4J executor version number based on ICU version

generateDataAndRun.sh, testdriver/testplan.py, verifier/verifier.py
=> Update handling of subdirectory creation

schema/check_generated_data.py, schema/check_schemas.py, schema/check_test_output.py, schema/schema_validator.py
This removes unnecessary logging that makes the log files harder to read.
=> Schema validations: reduce noise from unneeded logging messages

testgen/generators/localeDisplayNames.py, testgen/generators/plurals.py
=> Remove root locale from tests for locale names and plural rules

run_config.json
Simple fixes to better fill in the matrix of test results
=> Adding some missing tests in ICU4C

executors/cpp/coll.cpp, executors/cpp/datetime_fmt.cpp, executors/cpp/likely_subtags.cpp, executors/cpp/list_fmt.cpp, executors/cpp/localedisplaynames.cpp, executors/cpp/main.cpp, executors/cpp/number_fmt.cpp, executors/cpp/plural_rules.cpp, executors/cpp/relativedatetime_fmt.cpp, executors/cpp/rules.mk
Added so 'make clang' runs, updating files as suggested.
Updates .cpp files, too.
=> CPP files updated with clang

executors/dart_native/bin/executor.dart, run_config.json
This reverts commit e1dfd412ae4c497aab4ec2bbb5a0073df1528a9b.
=> Re-add more dart versions: 74, 75, and 76 after fixing extraneous error logging

executors/dart_web/bin/lang_names.dart, executors/dart_web/bin/likely_subtags.dart, executors/dart_web/out/executor.js
However, this doesn't work on my local machine. Perhaps some code is not being recompiled from these sources?
=> Reclassifying some failures as unsupported instead of errors

testdriver/testplan.py
=> Remove debug info from error level logging

executors/rust/src/datetime_2_beta2.rs
This gets it to about 3/5 passing. The rest needs a closer look. Unclear if they are bugs in ICU4X, the executor, or the test data.
=> Use the new options in ICU4X beta2 datetime

executors/rust/src/datetime_2_beta2.rs, schema/datetime_fmt/test_schema.json, testgen/generators/datetime_fmt.py
=> Add hourCycle option for date time formatting

run_config.json, testdriver/datasets.py, testgen/generators/datetime_fmt.py, testgen/generators/list_fmt.py, testgen/generators/relativedatetime_fmt.py, testgen/testdata_gen.py
=> Node JS 24 with ICU 77

executors/node/likely_subtags.js, testgen/testdata_gen.py
A small fix that removes failing tests from Node JS.
=> NodeJS likely subtags. Move some failures to unsupported

.github/workflows/dart.yaml, genData100.sh, generateDataAndRun.sh, run_config.json
Current PRs with changes unrelated to Dart are starting to [fail all of a sudden](https://github.com/unicode-org/conformance/actions/runs/15171956221/job/42738320686). This wasn't a problem in the [latest run on `main`](https://github.com/unicode-org/conformance/actions/runs/14935490521/job/41961798188) 2 weeks ago
=> Disable Dart Native in order to unblock CI

executors/cpp/coll.cpp, executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/collator/CollatorTester.java, executors/icu4j/74/executor-icu4j/src/test/java/org/unicode/conformance/collator/icu74/CollatorTest.java, executors/node/collator.js, schema/collation/result_schema.json, testdriver/testplan.py, testgen/generators/base.py, testgen/generators/collation.py, testgen/testdata_gen.py
#471 
This should change the number of test failures in ICU76 as follows:
ICU4C:  1557 --> 1444
ICU4J:     200 --> 163
ICU4X:    389 --> 319
More fixes to come!
=> Collation data generation fixes, reducing test failures

testgen/common.py, testgen/generators/lang_names.py, testgen/generators/localeDisplayNames.py
There were Syntax warnings that are fixed by this PR.
=> Fix some warnings with regex

executors/cpp/coll.cpp, executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/collator/CollatorInputJson.java, executors/icu4j/74/executor-icu4j/src/main/java/org/unicode/conformance/testtype/collator/CollatorTester.java, executors/icu4j/74/executor-icu4j/src/test/java/org/unicode/conformance/collator/icu74/CollatorTest.java, testgen/generators/collation.py
This resolves all ICU4J collation tests.
It also reduces ICU4C test failures from 79 to 7.
=> Fix collation test gen. Also resolve all Java and CPP executor test failures.
